# Generated by Django 4.2 on 2023-11-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etienda', '0004_alter_producto_category_alter_producto_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='rating',
        ),
        migrations.AlterField(
            model_name='producto',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagenes/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
