# Generated by Django 4.2 on 2023-11-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etienda', '0005_remove_producto_rating_alter_producto_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
