# Generated by Django 4.2 on 2023-11-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etienda', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
