# Generated by Django 4.2 on 2023-12-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etienda', '0008_alter_producto_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
